### ISSUE TITLE
 [ERR] [plugins/janus_textroom.c:janus_textroom_handle_incoming_request:2509] Room 43393483 already exists!

### ISSUE THREAD

**Issue by liujie12** [h-mdm/remote-control#40]
Every time the Android connects to the server, an exception occurs that the room number already exists. However, the room number is used for the first time and should not exist

**Comment by h-mdm** [comment]
Please try to restart the server by running the command
bash ./install.sh
This should fix the issue.

**Comment by liujie12** [comment]
[plugins/janus_textroom.c:janus_textroom_handle_incoming_request:2509] Room 34668306 already exists!   The preceding operations failed to resolve the exception, Above is the error,

**Comment by liujie12** [comment]
> 
[plugins/janus_textroom.c:janus_textroom_handle_incoming_request:2509] Room 34668306 already exists! The preceding operations failed to resolve the exception, Above is the error,

**Comment by liujie12** [comment]
> Please try to restart the server by running the command bash ./install.sh This should fix the issue.
After the above operation still cannot be solved, report an error
[plugins/janus_textroom.c:janus_textroom_handle_incoming_request:2509] Room 34668306 already exists! The preceding operations failed to resolve the exception, Above is the error
